@startuml
'https://plantuml.com/class-diagram

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

entity Event{
    *id
    --
    *name
    description
    *careTime
    lastRecordId: FK<Record.id>
    unit: FK<Unit.name>
    sumVal
    sumTime
}

entity Unit{
    *id
    --
    *name
}
Unit "0 or 1" |o-- Event


entity Record{
    *id
    --
    *eventId: FK<Event.id> (index)
    startTime(index)
    endTime(index)
    value
}


entity StepOffset{
    *id
    --
    *step
    *time
}

entity Steps{
    *id
    --
    *step
    *time(index)
}



@enduml