name: event_tracker
description: An event tracker in Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  fluttertoast: ^8.2.5
  intl: ^0.18.0
  fl_chart: 0.63.0
  sqflite: ^2.3.2
  drift: ^2.14.0
  drift_sqflite: ^2.0.1
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.42
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  drift_dev: ^2.14.1
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#assets:
#  - assets/data/shareQRCode.png
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
