// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTyn2TwGQ5GKREZy5-JQD7lCm3qadj5E',
    appId: '1:383831406976:web:9f068171f370092b88a965',
    messagingSenderId: '383831406976',
    projectId: 'event-tracker-22a80',
    authDomain: 'event-tracker-22a80.firebaseapp.com',
    storageBucket: 'event-tracker-22a80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqbqntc_56zUizMCOQgk8nkGtiUieang',
    appId: '1:383831406976:android:b2dffb12ef99130988a965',
    messagingSenderId: '383831406976',
    projectId: 'event-tracker-22a80',
    storageBucket: 'event-tracker-22a80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmScrVJGRkMvBjFZ0yLNBeKnNbs_bEiM',
    appId: '1:383831406976:ios:8851745e0b95c37888a965',
    messagingSenderId: '383831406976',
    projectId: 'event-tracker-22a80',
    storageBucket: 'event-tracker-22a80.appspot.com',
    iosClientId: '383831406976-59pklt72pnsv8no56do2ea4fbpk4pfve.apps.googleusercontent.com',
    iosBundleId: 'com.yuerguo.flutterEventTracker',
  );
}
